bff:
  home-url: http://localhost:5173
  client-url: http://localhost:8081
  login-url: ${bff.client-url}/oauth2/authorization/untitled-bff

server:
  port: 8081
  forward-headers-strategy: framework

spring:
  application:
    name: untitled-bff
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: ${KEYCLOAK_ISSUER_URI}
        registration:
          untitled-bff:
            provider: keycloak
            client-id: ${KEYCLOAK_CLIENT_ID}
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid,profile,email
  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: untitled-api
              uri: ${UNTITLED_API_URI:http://localhost:8082}
              predicates:
                - Path=/api/**
              filters:
                - TokenRelay=
                - StripPrefix=1

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when_authorized
